### ISSUE TITLE
ElasticSearchModuleBootstrapper error with neo4j community 2.3.1

### ISSUE THREAD

**Issue by adeze** [graphaware/neo4j-to-elasticsearch#1]
The log is showing an error preventing the module from loading
the UUID module does load correctly, 
and the config is set in server.properties and the neo4j.properties is set based on the docs for this is listed second (very minimal with optional stuff commented out--as they aren't relevant to my db)

```
13:38:22.738 [main] ERROR c.g.r.b.RuntimeKernelExtension - Unable to bootstrap module 2
java.lang.ClassNotFoundException: ElasticSearchModuleBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_45]
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:145) [graphaware-server-community-all-2.3.1.35.jar:na]
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113) [graphaware-server-community-all-2.3.1.35.jar:na]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:139) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:43) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.server.CommunityNeoServer$1.newGraphDatabase(CommunityNeoServer.java:66) [neo4j-server-2.3.1.jar:2.3.1]
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:95) [neo4j-server-2.3.1.jar:2.3.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111) [neo4j-kernel-2.3.1.jar:2.3.1,dd67f90]
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:194) [neo4j-server-2.3.1.jar:2.3.1]
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:97) [neo4j-server-2.3.1.jar:2.3.1]
	at org.neo4j.server.CommunityBootstrapper.start(CommunityBootstrapper.java:48) [neo4j-server-2.3.1.jar:2.3.1]
	at org.neo4j.server.CommunityBootstrapper.main(CommunityBootstrapper.java:35) [neo4j-server-2.3.1.jar:2.3.1]
13:38:22.739 [main] INFO  c.g.r.b.RuntimeKernelExtension - GraphAware Runtime bootstrapped, starting the Runtime...
13:38:22.751 [GraphAware Starter] INFO  c.g.runtime.BaseGraphAwareRuntime - Starting GraphAware...
```

neo4j.properties

```

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is uuid:
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#ES becomes the module ID:
com.graphaware.module.ES.2=ElasticSearchModuleBootstrapper

#URI of Elasticsearch
com.graphaware.module.ES.uri=localhost

#Port of Elasticsearch
com.graphaware.module.ES.port=9201

#optional, Elasticsearch index name, default is neo4j-index
com.graphaware.module.ES.index=neo4j-index

#optional, node property key of a propery that is used as unique identifier of the node. Must be the same as com.graphaware.module.UIDM.uuidProperty, defaults to uuid
com.graphaware.module.ES.keyProperty=uuid

#optional, whether to retry if a replication fails, defaults to false
com.graphaware.module.ES.retryOnError=false

#optional, size of the in-memory queue that queues up operations to be synchronised to Elasticsearch, defaults to 10000
com.graphaware.module.ES.queueSize=10000

#optional, specify which nodes to index in Elasticsearch, defaults to all nodes
#com.graphaware.module.ES.nodes=hasLabel('Person')

#optional, specify which node properties to index in Elasticsearch, defaults to all properties
#com.graphaware.module.ES.properties=key != 'age'

#optional, specify whether to send updates to Elasticsearch in bulk, defaults to true (highly recommended)
com.graphaware.module.ES.bulk=true

#optional, read explanation below, defaults to 0
com.graphaware.module.ES.reindexUntil=0
```

**Comment by adeze** [comment]
OK, figured it out 
the config was wrong -- the readme.md needs to be updated

the config that worked is

```
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper
```

not 

```
#ES becomes the module ID:
com.graphaware.module.ES.2=ElasticSearchModuleBootstrapper
```

**Comment by bachmanm** [comment]
fixed, thanks!

**Comment by Bennie1984** [comment]
Hi, 

I have a simaler problem and i'm a bit stuck now:

2018-04-13 08:47:45.619+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Unable to bootstrap module 2 Could not instantiate mapping class com.graphaware.module.es.mapping.JsonFileMapping : com.graphaware.module.es.mapping.JsonFileMapping
java.lang.RuntimeException: Could not instantiate mapping class com.graphaware.module.es.mapping.JsonFileMapping : com.graphaware.module.es.mapping.JsonFileMapping
	at com.graphaware.module.es.util.ServiceLoader.loadMapping(ServiceLoader.java:49)
	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:115)
	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:31)
	at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:66)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:84)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: java.lang.ClassNotFoundException: com.graphaware.module.es.mapping.JsonFileMapping
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.graphaware.module.es.util.ServiceLoader.loadMapping(ServiceLoader.java:25)
	... 20 more
