### ISSUE TITLE
java.lang.IllegalStateException: Service is not running!

### ISSUE THREAD

**Issue by yjhjeys** [graphaware/neo4j-to-elasticsearch#109]
`java.lang.IllegalStateException: Service is not running!
	at com.graphaware.writer.thirdparty.BaseThirdPartyWriter.offer(BaseThirdPartyWriter.java:91)
	at com.graphaware.writer.thirdparty.BaseThirdPartyWriter.write(BaseThirdPartyWriter.java:79)
	at com.graphaware.runtime.module.thirdparty.WriterBasedThirdPartyIntegrationModule.afterCommit(WriterBasedThirdPartyIntegrationModule.java:52)
	at com.graphaware.runtime.module.thirdparty.WriterBasedThirdPartyIntegrationModule.afterCommit(WriterBasedThirdPartyIntegrationModule.java:30)
	at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.afterCommit(BaseTxDrivenModuleManager.java:239)
	at com.graphaware.runtime.TxDrivenRuntime.afterCommit(TxDrivenRuntime.java:88)
	at com.graphaware.runtime.TxDrivenRuntime.afterCommit(TxDrivenRuntime.java:39)
	at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:158)
	at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:50)
	at org.neo4j.kernel.impl.api.TransactionHooks.afterCommit(TransactionHooks.java:78)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.afterCommit(KernelTransactionImplementation.java:677)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:617)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:468)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.commit(TransitionalTxManagementKernelTransaction.java:97)
	at org.neo4j.server.rest.transactional.TransactionHandle.closeContextAndCollectErrors(TransactionHandle.java:250)
	at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:158)
	at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:218)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:849)`

After performing a little time, this error occurs

**Comment by yjhjeys** [comment]
how can i solve it?

**Comment by nikhilRP** [comment]
I have been this issue, tried pretty much everything from tuning memory, increasing workers, gc etc. No success. @yjhjeys did you happen to find out the root cause of this issue?

**Comment by ikwattro** [comment]
Please write more details, Neo4j version, plugins versions, configuration
