### ISSUE TITLE
"dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware" causes errors

### ISSUE THREAD

**Issue by bradeac** [graphaware/neo4j-to-elasticsearch#137]
Hi,

I'm running a neo4j db in a docker container on my local machine. Everything works smooth.

Then I changed the dockerfile to copy those three .jar's  in the plugins folder and also add the configuration provided in the readme to the neo4j.conf file and I get errors and the container doesn't start anymore. Playing around with the configurations, I noticed that "dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware" breaks the whole thing.

Here is the output of the container:

2018-09-27 08:26:14.679+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/
graphaware]
2018-09-27 08:26:15.101+0000 ERROR The ResourceConfig instance does not contain any root res
ource classes.
2018-09-27 08:26:15.102+0000 WARN  unavailable The ResourceConfig instance does not contain
any root resource classes.
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contai
n any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUr
iRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicatio
nImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicati
onImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.j
ava:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initia
te(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandle
r.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:339)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:154)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(Abstrac
tNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
45)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
2018-09-27 08:26:15.104+0000 WARN  FAILED o.e.j.s.ServletContextHandler@39109603{/graphaware
,null,STARTING}: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-67
5230cd@f34bf670==org.neo4j.server.web.NeoServletContainer,-1,false org.neo4j.server.web.NeoS
ervletContainer-675230cd@f34bf670==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-675230cd@f34bf670==
org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandle
r.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:339)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:154)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(Abstrac
tNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
45)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does
 not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUr
iRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicatio
nImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicati
onImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.j
ava:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initia
te(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        ... 26 more
2018-09-27 08:26:15.106+0000 WARN  FAILED org.eclipse.jetty.server.handler.HandlerList@18df2
6a1[o.e.j.s.h.MovedContextHandler@5c459194{/,null,AVAILABLE}, o.e.j.s.ServletContextHandler@
39109603{/graphaware,null,STARTING}, o.e.j.s.ServletContextHandler@61d8a491{/db/manage,null,
null}, o.e.j.s.ServletContextHandler@6065bcb7{/db/data,null,null}, o.e.j.w.WebAppContext@1ee
6434{/browser,jar:file:/var/lib/neo4j/lib/neo4j-browser-3.1.14.jar!/browser,null}, o.e.j.s.S
ervletContextHandler@71d78cac{/,null,null}]: javax.servlet.ServletException: org.neo4j.serve
r.web.NeoServletContainer-675230cd@f34bf670==org.neo4j.server.web.NeoServletContainer,-1,fal
se org.neo4j.server.web.NeoServletContainer-675230cd@f34bf670==org.neo4j.server.web.NeoServl
etContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-675230cd@f34bf670==
org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandle
r.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:339)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:154)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(Abstrac
tNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
45)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does
 not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUr
iRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicatio
nImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicati
onImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.j
ava:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initia
te(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        ... 26 more
2018-09-27 08:26:15.128+0000 WARN  FAILED org.eclipse.jetty.server.Server@6c1a63f7: javax.se
rvlet.ServletException: org.neo4j.server.web.NeoServletContainer-675230cd@f34bf670==org.neo4
j.server.web.NeoServletContainer,-1,false org.neo4j.server.web.NeoServletContainer-675230cd@
f34bf670==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-675230cd@f34bf670==
org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandle
r.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:339)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:154)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(Abstrac
tNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
45)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does
 not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUr
iRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicatio
nImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicati
onImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.j
ava:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initia
te(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        ... 26 more
2018-09-27 08:26:15.129+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474: org.neo4j.server.w
eb.NeoServletContainer-675230cd@f34bf670==org.neo4j.server.web.NeoServletContainer,-1,false
2018-09-27 08:26:15.153+0000 INFO  Stopping...
2018-09-27 08:26:15.276+0000 INFO  Stopped.
2018-09-27 08:26:15.287+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component '
org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@630c3af3' was successful
ly initialized, but failed to start. Please see the attached cause exception "The ResourceCo
nfig instance does not contain any root resource classes.". Starting Neo4j failed: Component
 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@630c3af3' was successf
ully initialized, but failed to start. Please see the attached cause exception "The Resource
Config instance does not contain any root resource classes.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.
AbstractNeoServer$ServerComponentsLifecycleAdapter@630c3af3' was successfully initialized, b
ut failed to start. Please see the attached cause exception "The ResourceConfig instance doe
s not contain any root resource classes.".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(Serv
erStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.Abstra
ctNeoServer$ServerComponentsLifecycleAdapter@630c3af3' was successfully initialized, but fai
led to start. Please see the attached cause exception "The ResourceConfig instance does not
contain any root resource classes.".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
66)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-675230cd
@f34bf670==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandle
r.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java
:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.ja
va:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:6
8)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:339)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:154)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
        at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
        at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(Abstrac
tNeoServer.java:541)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:4
45)
        ... 5 more
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does
 not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUr
iRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicatio
nImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicati
onImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl
.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplication
Impl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.j
ava:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initia
te(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:
577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
        ... 26 more
2018-09-27 08:26:15.296+0000 INFO  Neo4j Server shutdown initiated by request

Any help would be appreciated.
Thank you

**Comment by ikwattro** [comment]
The error you get means that the plugins are not found, make sure you have the neo4j-framework-server jar correctly mounted in docker as well as the other plugins you are using

**Comment by bradeac** [comment]
That might be true. For the moment we drifted away from using a plugin and went on to build our own solution. You can close the issue for now and I will come back later with a conclusion whether the plugins weren't there or it was something else.
Thank you.
