### ISSUE TITLE
ERROR Failed to start Neo4j: Starting Neo4j failed

### ISSUE THREAD

**Issue by faizankarim** [graphaware/neo4j-to-elasticsearch#168]
**Neo4j version: 3.5.14

jars in plugin:
graphaware-server-all-3.5.14.55.jar  
neo4j-to-elasticsearch-3.5.14.55.10.jar  
uuid-3.5.14.55.19.jar**

**neo4j config:**
# This setting should only be set once for registering the framework and all the used submodules
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is "uuid". (only if using the UUID module)
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#prevent the whole db to be assigned a new uuid if the uuid module is settle up together with neo4j2es
com.graphaware.module.UIDM.initializeUntil=0

#ES becomes the module ID:
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper

#URI of Elasticsearch
com.graphaware.module.ES.uri=0.0.0.0

#Port of Elasticsearch
com.graphaware.module.ES.port=9200

#optional, protocol of Elasticsearch connection, defaults to http
com.graphaware.module.ES.protocol=http

#optional, Elasticsearch index name, default is neo4j-index
com.graphaware.module.ES.index=neo4j-index

#optional, node property key of a propery that is used as unique identifier of the node. Must be the same as com.graphaware.module.UIDM.uuidProperty (only if using UUID module), defaults to uuid
#use "ID()" to use native Neo4j IDs as Elasticsearch IDs (not recommended)
com.graphaware.module.ES.keyProperty=uuid

#optional, whether to retry if a replication fails, defaults to false
com.graphaware.module.ES.retryOnError=false

#optional, size of the in-memory queue that queues up operations to be synchronised to Elasticsearch, defaults to 10000
com.graphaware.module.ES.queueSize=10000

#optional, size of the batch size to use during re-initialization, defaults to 1000
com.graphaware.module.ES.reindexBatchSize=2000

#optional, specify which nodes to index in Elasticsearch, defaults to all nodes
com.graphaware.module.ES.node=hasLabel('Person')

#optional, specify which node properties to index in Elasticsearch, defaults to all properties
com.graphaware.module.ES.node.property=key != 'age'

#optional, specify whether to send updates to Elasticsearch in bulk, defaults to true (highly recommended)
com.graphaware.module.ES.bulk=true

#optional, read explanation below, defaults to 0
com.graphaware.module.ES.initializeUntil=0

#optional, whether or not the reindexation process (when db start) should be made in asynchronous mode
#default is "false" and the db will not be available until completed
#com.graphaware.module.ES.asyncIndexation=true

**Console output:**
Active database: graph.db
Directories in use:
  home:         /home/faizankarim550/neo4j-community-3.5.14
  config:       /home/faizankarim550/neo4j-community-3.5.14/conf
  logs:         /home/faizankarim550/neo4j-community-3.5.14/logs
  plugins:      /home/faizankarim550/neo4j-community-3.5.14/plugins
  import:       /home/faizankarim550/neo4j-community-3.5.14/import
  data:         /home/faizankarim550/neo4j-community-3.5.14/data
  certificates: /home/faizankarim550/neo4j-community-3.5.14/certificates
  run:          /home/faizankarim550/neo4j-community-3.5.14/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2020-08-27 12:45:34.676+0000 INFO  ======== Neo4j 3.5.14 ========
2020-08-27 12:45:34.695+0000 INFO  Starting...
2020-08-27 12:45:36.733+0000 INFO  GraphAware Runtime enabled, bootstrapping...
2020-08-27 12:45:36.758+0000 INFO  Bootstrapping module with order 1, ID UIDM, using com.graphaware.module.uuid.UuidBootstrapper
2020-08-27 12:45:36.822+0000 INFO  UIDM (re-)initialize until set to NEVER
2020-08-27 12:45:36.860+0000 INFO  Node Inclusion Policy set to com.graphaware.common.policy.inclusion.composite.CompositeNodeInclusionPolicy@91441472
2020-08-27 12:45:36.860+0000 INFO  uuidProperty set to uuid
2020-08-27 12:45:36.860+0000 INFO  uuidIndex set to uuidIndex
2020-08-27 12:45:36.867+0000 INFO  Registering module UIDM with GraphAware Runtime.
2020-08-27 12:45:36.868+0000 INFO  Bootstrapping module with order 2, ID ES, using com.graphaware.module.es.ElasticSearchModuleBootstrapper
2020-08-27 12:45:36.955+0000 INFO  Shutting down GraphAware Runtime... 
2020-08-27 12:45:36.956+0000 INFO  Shutting down module UIDM
2020-08-27 12:45:36.956+0000 INFO  Terminating task scheduler...
2020-08-27 12:45:36.956+0000 INFO  Task scheduler terminated successfully.
2020-08-27 12:45:36.956+0000 INFO  GraphAware Runtime shut down.
2020-08-27 12:45:36.960+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@bdc8014' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@bdc8014' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@bdc8014' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@bdc8014' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /home/faizankarim550/neo4j-community-3.5.14/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@f8f56b9' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
        ... 9 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@4d23015c' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:459)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@4d23015c' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: io/searchbox/action/Action
        at com.graphaware.module.es.ElasticSearchConfiguration.<clinit>(ElasticSearchConfiguration.java:37)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:52)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:31)
        at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:60)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 29 more
2020-08-27 12:45:36.961+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by Tak1za** [comment]
@faizankarim I'm assuming this problem got fixed for you, may I know how?

**Comment by faizankarim** [comment]
@Tak1za download plugins from maven repo.

**Comment by Tak1za** [comment]
Yeah that seemed to solve the problem. I wonder what the difference is between the one here and that from maven repo
