### ISSUE TITLE
Unable to start indexing: java.lang.ClassNotFoundException: org.omg.CORBA.portable.IDLEntity

### ISSUE THREAD

**Issue by Tak1za** [graphaware/neo4j-to-elasticsearch#169]
I am using the following Neo4j and plugin version:
Neo4j community : 3.5.22
graphaware-server-all-3.5.14.55.jar
neo4j-to-elasticsearch-3.5.14.55.10.jar
uuid-3.5.14.55.19.jar

Following is the error message as soon as I start adding a node to Neo4j:

```
2021-01-07 15:18:10.662+0000 ERROR Error while executing background job because of the following exception (the task will be killed): Transaction was marked as successful, but unable to commit transaction so rolled back.
org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
        at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:99)
        at apoc.util.Util.lambda$inTxFuture$4(Util.java:240)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: org/omg/CORBA/portable/IDLEntity
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:668)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:594)
        at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
        at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:77)
        ... 5 more
Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/IDLEntity
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.graphaware.common.uuid.EaioUuidGenerator.generateUuid(EaioUuidGenerator.java:31)
        at com.graphaware.module.uuid.UuidModule.assignNewUuid(UuidModule.java:192)
        at com.graphaware.module.uuid.UuidModule.assignUuid(UuidModule.java:183)
        at com.graphaware.module.uuid.UuidModule.processEntities(UuidModule.java:138)
        at com.graphaware.module.uuid.UuidModule.beforeCommit(UuidModule.java:129)
        at com.graphaware.module.uuid.UuidModule.beforeCommit(UuidModule.java:39)
        at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.beforeCommit(BaseTxDrivenModuleManager.java:204)
        at com.graphaware.runtime.TxDrivenRuntime.beforeCommit(TxDrivenRuntime.java:76)
        at com.graphaware.runtime.TxDrivenRuntime.beforeCommit(TxDrivenRuntime.java:39)
        at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:123)
        at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:48)
        at org.neo4j.kernel.impl.api.TransactionHooks.beforeCommit(TransactionHooks.java:59)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:664)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.IDLEntity
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 30 more
```

The error appears only while using the UUID plugin.

Following is my neo4j.conf related to graphaware:

```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true

com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.UIDM.uuidProperty=id
# com.graphaware.module.UIDM.relationship=(true)

com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper
com.graphaware.module.ES.uri=localhost
com.graphaware.module.ES.port=9200
com.graphaware.module.ES.protocol=http
com.graphaware.module.ES.index=varun-new-index
# com.graphaware.module.ES.mapping=AdvancedMapping
com.graphaware.module.ES.keyProperty=id
com.graphaware.module.ES.queueSize=1000
com.graphaware.module.ES.retryOnError=false
com.graphaware.module.ES.asyncIndexation=false
com.graphaware.module.ES.initializeUntil=20000000000000
com.graphaware.module.ES.bulk=true
com.graphaware.module.ES.relationship=(true)
com.graphaware.module.ES.mapping=com.graphaware.module.es.mapping.JsonFileMapping
com.graphaware.module.ES.file=mapping.json
 
com.graphaware.runtime.stats.disabled=true
com.graphaware.server.stats.disabled=true
```

And this is my mapping.json:

```
{
	"defaults": {
		"nodes_index": "varun-neo4j-nodes",
		"key_property": "uuid",
		"relationships_index": "varun-neo4j-relationships",
		"blacklisted_node_properties": [
			"qudt.conversionMultiplier"
		],
		"include_remaining_properties": true
	},
	"node_mappings": [
		{
			"condition": "allNodes()",
			"type": "nodes"
		}
	],
	"relationship_mappings": [
		{
			"condition": "allRelationships()",
			"type": "relationships",
			"properties": {
				"startNodeLabels": "getStartNode().getLabels()",
				"endNodeLabels": "getEndNode().getLabels()"
			}
		}
	]
}
```

**Comment by Tak1za** [comment]
I found a fix for this:
Downloading the jar from here: https://repo1.maven.org/maven2/org/ow2/jonas/osgi/corba-api/5.0.1/
And putting it inside the plugins folder seems to fix the issue.
