### ISSUE TITLE
Can type parameter be made dynamic?

### ISSUE THREAD

**Issue by foobargeez** [graphaware/neo4j-to-elasticsearch#34]
The idea is to be able to call functions in `type` parameter, so data organization is more more dynamic.  See the below for example:

```
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "getType()"
    }
  ]
```

Currently, it fails with the following error:
```
2016-07-31 17:08:59.496+0000 ERROR [c.g.m.e.m.j.DocumentMappingRepresentation] Error while creating relationship: com.graphaware.common.representation.RelationshipRepresentation@d4e225b4 EL1004E:(pos 0): Method call: Method getType() cannot be found on com.graphaware.module.es.mapping.json.RelationshipExpression type
org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 0): Method call: Method getType() cannot be found on com.graphaware.module.es.mapping.json.RelationshipExpression type
	at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:211)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:125)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:85)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:153)
	at com.graphaware.module.es.mapping.json.GraphDocumentMapper.getType(GraphDocumentMapper.java:130)
	at com.graphaware.module.es.mapping.json.GraphDocumentMapper.getDocumentRepresentation(GraphDocumentMapper.java:184)
	at com.graphaware.module.es.mapping.json.GraphDocumentMapper.getDocumentRepresentation(GraphDocumentMapper.java:159)
	at com.graphaware.module.es.mapping.json.DocumentMappingRepresentation.createOrUpdateRelationship(DocumentMappingRepresentation.java:79)
	at com.graphaware.module.es.mapping.JsonFileMapping.createRelationship(JsonFileMapping.java:96)
	at com.graphaware.module.es.mapping.JsonFileMapping.getActions(JsonFileMapping.java:76)
	at com.graphaware.module.es.ElasticSearchWriter.processOperations(ElasticSearchWriter.java:108)
	at com.graphaware.writer.thirdparty.BaseThirdPartyWriter.runOneIteration(BaseThirdPartyWriter.java:63)
	at com.google.common.util.concurrent.AbstractScheduledService$1$1.run(AbstractScheduledService.java:174)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks in advance!

**Comment by ikwattro** [comment]
Thanks for the report, I'll check that normally it should work.

**Comment by ikwattro** [comment]
So it wasn't there. I added it, will ship in next release.
