### ISSUE TITLE
export: `= com.graphaware.module.es.mapping.JsonFileMapping': not a valid identifier

### ISSUE THREAD

**Issue by sebolek** [graphaware/neo4j-to-elasticsearch#37]
When i try to configure neo4j to Elastic search in "neo4j.conf" Neo4j fails to start with the folowing error:

 [~/neo4j-community-3.0.4]# ./bin/neo4j console
./bin/neo4j-shared.sh: line 146: export: `= com.graphaware.module.es.mapping.JsonFileMapping': not a valid identifier

These are the 2 lines I try to add in order to implement Mappings:

com.graphaware.module.ES.mapping = com.graphaware.module.ES.mapping.JsonFileMapping
com.graphaware.module.ES.file = mapping.json

Thanks in advance!
Seb

**Comment by bachmanm** [comment]
could you try to remove the spaces around the `=` sign, capitalize everything properly (incl. package names) and report back pls if you still have a problem

**Comment by sebolek** [comment]
ok, i removed the spaces around =  Now Neo4j starts, but i get the following ERROR

bchomez@bchomez.com [~/neo4j-community-3.0.4]# ./bin/neo4j console
Starting Neo4j.
2016-08-10 18:13:43.574+0000 INFO  Starting...
2016-08-10 18:13:44.632+0000 INFO  Bolt enabled on localhost:7687.
2016-08-10 18:13:48.724+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2016-08-10 18:13:48.740+0000 INFO  Running in a single-node architecture (Neo4j Community)
2016-08-10 18:13:48.749+0000 INFO  [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID UIDM, using com.graphaware.module.uuid.UuidBootstrapper
2016-08-10 18:13:48.846+0000 INFO  Relationship Inclusion Policy set to com.graphaware.common.policy.composite.CompositeRelationshipInclusionPolicy@cc687ea7
2016-08-10 18:13:48.847+0000 INFO  uuidProperty set to uuid
2016-08-10 18:13:48.851+0000 INFO  Registering module UIDM with GraphAware Runtime.
2016-08-10 18:13:48.851+0000 INFO  [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 2, ID ES, using com.graphaware.module.es.ElasticSearchModuleBootstrapper
2016-08-10 18:13:48.857+0000 INFO  ElasticSearch index-prefix set to neo4j-index
2016-08-10 18:13:48.857+0000 INFO  ElasticSearch key-property set to uuid
2016-08-10 18:13:48.858+0000 INFO  ElasticSearch force-strings set to false
2016-08-10 18:13:48.858+0000 INFO  ES (re-)initialize until set to NEVER
2016-08-10 18:13:48.862+0000 INFO  Node Property Inclusion Policy set to com.graphaware.common.policy.composite.CompositeNodePropertyInclusionPolicy@12ba5a68
2016-08-10 18:13:48.862+0000 INFO  Relationship Inclusion Policy set to com.graphaware.common.policy.composite.CompositeRelationshipInclusionPolicy@cc687ea7
2016-08-10 18:13:48.863+0000 INFO  Elasticsearch URI set to localhost
2016-08-10 18:13:48.863+0000 INFO  Elasticsearch port set to 9200
2016-08-10 18:13:48.863+0000 INFO  Elasticsearch key property set to uuid
2016-08-10 18:13:48.863+0000 INFO  Elasticsearch retry-on-error set to false
2016-08-10 18:13:48.863+0000 INFO  Elasticsearch module queue capacity set to 1000
2016-08-10 18:13:48.864+0000 INFO  Elasticsearch bulk execution set to true
2016-08-10 18:13:48.864+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Unable to bootstrap module 2 Could not instantiate mapping class com.graphaware.module.ES.mapping.JsonFileMapping : com.graphaware.module.ES.mapping.JsonFileMapping
java.lang.RuntimeException: Could not instantiate mapping class com.graphaware.module.ES.mapping.JsonFileMapping : com.graphaware.module.ES.mapping.JsonFileMapping
	at com.graphaware.module.es.util.ServiceLoader.loadMapping(ServiceLoader.java:49)
	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:95)
	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:32)
	at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:66)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:55)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: java.lang.ClassNotFoundException: com.graphaware.module.ES.mapping.JsonFileMapping
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.graphaware.module.es.util.ServiceLoader.loadMapping(ServiceLoader.java:25)
	... 21 more
2016-08-10 18:13:48.866+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2016-08-10 18:13:54.027+0000 INFO  Starting GraphAware...
2016-08-10 18:13:54.029+0000 INFO  Loading module metadata...
2016-08-10 18:13:54.029+0000 INFO  Loading metadata for module UIDM
2016-08-10 18:13:54.074+0000 INFO  Module UIDM seems to have been registered before, metadata loaded successfully.
2016-08-10 18:13:54.074+0000 INFO  Module UIDM seems to have changed configuration since last run, will try to re-initialize...
2016-08-10 18:13:54.074+0000 INFO  InitializeUntil set to 9223372036854775807 and it is 1470852834074. Will re-initialize.
2016-08-10 18:13:55.430+0000 INFO  Started.
2016-08-10 18:13:57.027+0000 INFO  Remote interface available at http://0.0.0.0:7474/
2016-08-10 18:13:57.080+0000 INFO  Module metadata loaded.
2016-08-10 18:13:57.080+0000 INFO  Starting transaction-driven modules...
2016-08-10 18:13:57.080+0000 INFO  Transaction-driven modules started.
2016-08-10 18:13:57.080+0000 INFO  There are no timer-driven runtime modules. Not scheduling any tasks.
2016-08-10 18:13:57.081+0000 INFO  GraphAware started.
2016-08-10 18:13:57.081+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime automatically started.

**Comment by bachmanm** [comment]
please make sure you capitalize everything properly incl. package names. I think it should be "es", not "ES" in `com.graphaware.module.ES.mapping.JsonFileMapping`

**Comment by sebolek** [comment]
Yay! it worked! Thanks a lot, i've been stuck with this one for over a week...
Seb
