### ISSUE TITLE
fail neo4j on start

### ISSUE THREAD

**Issue by farhoud** [graphaware/neo4j-to-elasticsearch#53]
hi
we try to add neo4j-to-elasticsearch to official neo4j docker but it broke neo4j:
here is my docker-compose:
```yaml
version: '2'
services:
  neo4j:
    image: neo4j:3.1
    volumes:
     - ./data:/data
     - ./logs:/logs
     - ./conf:/conf
     - ./plugins:/plugins
    ports:
     - "7475:7474"
     - "7688:7687"
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    links:
     - elastic 
    depends_on:
     - elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
     - IPC_LOCK
    volumes:
     - esdata1:/usr/share/elasticsearch/data
    ports:
     - 9200:9200
volumes:
  esdata1:
    driver: local
```

here is my neo4j conf:
```

```conf
#*****************************************************************
# Neo4j configuration
#*****************************************************************

# The name of the database to mount
#dbms.active_database=graph.db

# Paths of directories in the installation.
#dbms.directories.data=data
#dbms.directories.plugins=plugins
#dbms.directories.certificates=certificates

# This setting constrains all `LOAD CSV` import files to be under the `import` directory. Remove or uncomment it to
# allow files to be loaded from anywhere in filesystem; this introduces possible security problems. See the `LOAD CSV`
# section of the manual for details.
dbms.directories.import=import

# Whether requests to Neo4j are authenticated.
# To disable authentication, uncomment this line
dbms.security.auth_enabled=false

# Enable this to be able to upgrade a store from an older version.
#dbms.allow_format_migration=true

# The amount of memory to use for mapping the store files, in bytes (or
# kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g').
# If Neo4j is running on a dedicated server, then it is generally recommended
# to leave about 2-4 gigabytes for the operating system, give the JVM enough
# heap to hold all your transaction state and query context, and then leave the
# rest for the page cache.
# The default page cache memory assumes the machine is dedicated to running
# Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size.
dbms.memory.pagecache.size=512M

#*****************************************************************
# Network connector configuration
#*****************************************************************

# Bolt connector
dbms.connector.bolt.type=BOLT
dbms.connector.bolt.enabled=true
dbms.connector.bolt.tls_level=OPTIONAL
# To have Bolt accept non-local connections, uncomment this line
dbms.connector.bolt.address=0.0.0.0:7687

# HTTP Connector
dbms.connector.http.type=HTTP
dbms.connector.http.enabled=true
#dbms.connector.http.encryption=NONE
# To have HTTP accept non-local connections, uncomment this line
dbms.connector.http.address=0.0.0.0:7474

# HTTPS Connector
dbms.connector.https.type=HTTP
dbms.connector.https.enabled=true
dbms.connector.https.encryption=TLS
dbms.connector.https.address=0.0.0.0:7473

# Number of Neo4j worker threads.
#dbms.threads.worker_count=

#*****************************************************************
# Logging configuration
#*****************************************************************

# To enable HTTP logging, uncomment this line
#dbms.logs.http.enabled=true

# To enable GC Logging, uncomment this line
#dbms.logs.gc.enabled=true

# GC Logging Options
# see http://docs.oracle.com/cd/E19957-01/819-0084-10/pt_tuningjava.html#wp57013 for more information.
#dbms.logs.gc.options=-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution

# Number of GC logs to keep.
#dbms.logs.gc.rotation.keep_number=5

# Size of each GC log that is kept.
#dbms.logs.gc.rotation.size=20m

# Size threshold for rotation of the debug log. If set to zero then no rotation will occur. Accepts a binary suffix "k",
# "m" or "g".
#dbms.logs.debug.rotation.size=20m

# Maximum number of history files for the internal log.
#dbms.logs.debug.rotation.keep_number=7

#*****************************************************************
# Miscellaneous configuration
#*****************************************************************

# Enable this to specify a parser other than the default one.
#cypher.default_language_version=3.0

# Determines if Cypher will allow using file URLs when loading data using
# `LOAD CSV`. Setting this value to `false` will cause Neo4j to fail `LOAD CSV`
# clauses that load data from the file system.
#dbms.security.allow_csv_import_from_file_urls=true

# Retention policy for transaction logs needed to perform recovery and backups.
dbms.tx_log.rotation.retention_policy=100M size

# Enable a remote shell server which Neo4j Shell clients can log in to.
#dbms.shell.enabled=true
# The network interface IP the shell will listen on (use 0.0.0.0 for all interfaces).
#dbms.shell.host=127.0.0.1
# The port the shell will listen on, default is 1337.
#dbms.shell.port=1337

# Only allow read operations from this Neo4j instance. This mode still requires
# write access to the directory for lock purposes.
#dbms.read_only=false

# Comma separated list of JAX-RS packages containing JAX-RS resources, one
# package name for each mountpoint. The listed package names will be loaded
# under the mountpoints specified. Uncomment this line to mount the
# org.neo4j.examples.server.unmanaged.HelloWorldResource.java from
# neo4j-server-examples under /examples/unmanaged, resulting in a final URL of
# http://localhost:7474/examples/unmanaged/helloworld/{nodeId}
#dbms.unmanaged_extension_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true



#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is "uuid".
#use "ID()" to use native Neo4j IDs as Elasticsearch IDs
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#prevent the whole db to be assigned a new uuid if the uuid module is settle up together with neo4j2es
com.graphaware.module.UIDM.initializeUntil=0
com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex
#ES becomes the module ID:
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper

#URI of Elasticsearch
com.graphaware.module.ES.uri=0.0.0.0

#Port of Elasticsearch
com.graphaware.module.ES.port=9200

#optional, Elasticsearch index name, default is neo4j-index
com.graphaware.module.ES.index=neo4j-index

#optional, node property key of a propery that is used as unique identifier of the node. Must be the same as com.graphaware.module.UIDM.uuidProperty, defaults to uuid
com.graphaware.module.ES.keyProperty=uuid

#optional, whether to retry if a replication fails, defaults to false
com.graphaware.module.ES.retryOnError=false

#optional, size of the in-memory queue that queues up operations to be synchronised to Elasticsearch, defaults to 10000
com.graphaware.module.ES.queueSize=10000

#optional, size of the batch size to use during re-initialization, defaults to 1000
com.graphaware.module.ES.reindexBatchSize=2000

#optional, specify which nodes to index in Elasticsearch, defaults to all nodes
#com.graphaware.module.ES.node=hasLabel('Person')

#optional, specify which node properties to index in Elasticsearch, defaults to all properties
#com.graphaware.module.ES.node.property=key != 'age'

#optional, specify whether to send updates to Elasticsearch in bulk, defaults to true (highly recommended)
com.graphaware.module.ES.bulk=true

#optional, read explanation below, defaults to 0
com.graphaware.module.ES.initializeUntil=0
```

modules using:
  graphaware,  time-tree, uuid, es all version 3.1

neo4j:
   official docker image version 3.1

error log :
```log
neo4j_1    | 2016-12-29 14:53:42.622+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1466813' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1466813' was successfully initialized, but failed to start. Please see attached cause exception.
neo4j_1    | org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1466813' was successfully initialized, but failed to start. Please see attached cause exception.
neo4j_1    | 	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
neo4j_1    | 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
neo4j_1    | 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
neo4j_1    | 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
neo4j_1    | 	at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
neo4j_1    | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1466813' was successfully initialized, but failed to start. Please see attached cause exception.
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
neo4j_1    | 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
neo4j_1    | 	... 3 more
neo4j_1    | Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
neo4j_1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
neo4j_1    | 	at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
neo4j_1    | 	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:90)
neo4j_1    | 	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
neo4j_1    | 	... 5 more
neo4j_1    | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@5adda598' was successfully initialized, but failed to start. Please see attached cause exception.
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
neo4j_1    | 	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
neo4j_1    | 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
neo4j_1    | 	... 9 more
neo4j_1    | Caused by: java.lang.NoClassDefFoundError: io/searchbox/action/Action
neo4j_1    | 	at com.graphaware.module.es.ElasticSearchConfiguration.<clinit>(ElasticSearchConfiguration.java:36)
neo4j_1    | 	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:49)
neo4j_1    | 	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:32)
neo4j_1    | 	at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:60)
neo4j_1    | 	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
neo4j_1    | 	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
neo4j_1    | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
neo4j_1    | 	... 14 more
neo4j_1    | Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
neo4j_1    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
neo4j_1    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
neo4j_1    | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
neo4j_1    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
neo4j_1    | 	... 21 more
```

**Comment by farhoud** [comment]
try with 3.0.7 same issue

**Comment by farhoud** [comment]
change graphaware-neo4j-to-elasticsearch-3.1.0.44.8.jar to
this one not has io ---> graphaware-neo4j-to-elasticsearch-3.1.0.44.7.jar
and fixed

**Comment by ikwattro** [comment]
Thanks for reporting this @farhoud , seems like the last build should be fixed though.

**Comment by isaacuribe** [comment]
FYI, it looks like another .8 release was truncated, I got the same error when trying to use the 3.0.7.44.8 JAR:

...
neo4j_1          | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@5e128aa2' was successfully initialized, but failed to start. Please see attached cause exception.
...
neo4j_1          | Caused by: java.lang.NoClassDefFoundError: io/searchbox/action/Action
...

I noticed that the file is oddly only 68K, tried with graphaware-neo4j-to-elasticsearch-3.0.7.44.7.jar , that one is working (size is 2.8M).

The apparently broken file is: https://products.graphaware.com/download/neo4j-to-elasticsearch/graphaware-neo4j-to-elasticsearch-3.0.7.44.8.jar

Thanks for the plugin!!
