### ISSUE TITLE
failed to start neo4j with ElasticSearchModuleBootstrapper

### ISSUE THREAD

**Issue by lojul** [graphaware/neo4j-to-elasticsearch#54]
i am using 
neo4j: version 3.1, 
plug-ins: 
graphaware-neo4j-to-elasticsearch-3.1.0.44.8.jar; 
graphaware-uuid-3.1.0.44.13.jar; 
graphaware-server-community-all-3.1.0.44.jar;
ElasticSearch: 5.1.1

Below is my neo4j.conf graphaware related configuration:

#This setting should only be set once for registering the framework and all the used submodules
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware 

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is "uuid".
#use "ID()" to use native Neo4j IDs as Elasticsearch IDs
#com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is uuidIndex
#com.graphaware.module.UIDM.uuidIndex=uuidIndex

#prevent the whole db to be assigned a new uuid if the uuid module is settle up together with neo4j2es
com.graphaware.module.UIDM.initializeUntil=0

#ES becomes the module ID:
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper

#URI of Elasticsearch
com.graphaware.module.ES.uri=10.0.0.204

#Port of Elasticsearch
com.graphaware.module.ES.port=9210

#optional, specify the Shield user
com.graphaware.module.ES.authUser=elastic

#optional, specify the Shield password
com.graphaware.module.ES.authPassword=changeme

below is my log:
nohup: ignoring input
2016-12-30 07:07:52.229+0000 INFO  Starting...
2016-12-30 07:07:53.088+0000 INFO  Bolt enabled on 10.0.0.204:7687.
2016-12-30 07:07:56.686+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2016-12-30 07:07:56.705+0000 INFO  Running in a single-node architecture (Neo4j Community)
2016-12-30 07:07:56.716+0000 INFO  [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID UIDM, using com.graphaware.module.uuid.UuidBootstrapper
2016-12-30 07:07:56.820+0000 INFO  UIDM (re-)initialize until set to NEVER
2016-12-30 07:07:56.829+0000 INFO  Registering module UIDM with GraphAware Runtime.
2016-12-30 07:07:56.830+0000 INFO  [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 2, ID ES, using com.graphaware.module.es.ElasticSearchModuleBootstrapper
2016-12-30 07:07:56.936+0000 INFO  Shutting down GraphAware Runtime...
2016-12-30 07:07:56.937+0000 INFO  Shutting down module UIDM
2016-12-30 07:07:56.937+0000 INFO  Terminating task scheduler...
2016-12-30 07:07:56.937+0000 INFO  Task scheduler terminated successfully.
2016-12-30 07:07:56.937+0000 INFO  GraphAware Runtime shut down.
2016-12-30 07:07:56.947+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3c6bf0ad' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3c6bf0ad' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3c6bf0ad' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3c6bf0ad' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
       at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /apps/neo4j-community-3.1.0/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@487b5b61' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: io/searchbox/action/Action
        at com.graphaware.module.es.ElasticSearchConfiguration.<clinit>(ElasticSearchConfiguration.java:36)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:49)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:32)
        at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:60)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 21 more

**Comment by ikwattro** [comment]
@lojul 

Thx for the report.

Can you try with the version 7 of the module, http://products.graphaware.com/download/neo4j-to-elasticsearch/graphaware-neo4j-to-elasticsearch-3.1.0.44.7.jar

Thanks !

**Comment by maddoc1** [comment]
I can confirm that version 7 works correctly with this configuration and version 8 crashes with the same error.

**Comment by ikwattro** [comment]
Thanks, we will remove version8 the time we can look into it
