### ISSUE TITLE
mapping.json does not load from conf file

### ISSUE THREAD

**Issue by CerebralUnit** [graphaware/neo4j-to-elasticsearch#60]
Hey guys,

I've got the Enterprise version of Neo4j and when I use the following config settings:

com.graphaware.module.ES.mapping=com.graphaware.module.es.mapping.JsonFileMapping
com.graphaware.module.ES.file=mapping.json

I get an error:

java.lang.RuntimeException: Unable to read json mapping file
        at com.graphaware.module.es.mapping.JsonFileMapping.configure(JsonFileMapping.java:53)
        at com.graphaware.module.es.ElasticSearchConfiguration.withMapping(ElasticSearchConfiguration.java:133)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:102)
        at com.graphaware.module.es.ElasticSearchModuleBootstrapper.doBootstrapModule(ElasticSearchModuleBootstrapper.java:32)
        at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:66)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
        at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:90)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: java.io.FileNotFoundException: class path resource [mapping.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/C:/Program%20Files/Neo4j%20Enterprise%203.1.0/plugins/graphaware-neo4j-to-elasticsearch-3.1.0.44.7.jar!/mapping.json
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218)
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
        at com.graphaware.module.es.mapping.JsonFileMapping.configure(JsonFileMapping.java:50)
        ... 21 more

I've tried using the prefixes "file:", "classpath:", "classpath*:" etc.. Any idea why?

**Comment by ikwattro** [comment]
Thanks for the report. It seems the classpath is different on windows (which I cannot test unfortunately). Can you try to put the json file in the plugins directory ?

**Comment by CerebralUnit** [comment]
Hi, I've tried to put the json file in the plugins folder and it threw the same error. This line in the stack trace above seems to imply that it's checking inside of the jar file of the plugin:

jar:file:/C:/Program%20Files/Neo4j%20Enterprise%203.1.0/plugins/graphaware-neo4j-to-elasticsearch-3.1.0.44.7.jar!/mapping.json

I don't know why the exclamation point appears in the path, but If its classpath is the jar file, then getting the resource might have to be done by using "getResourceAsStream()." I've tried moving the mapping.json file to as many places I could think would make sense to no avail.
