### ISSUE TITLE
Failure to send stats should be silent

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#84]
Found this in a customer's Neo4j log:
```
2017-09-28 08:16:42.295+0000 WARN  Unable to collect stats www.google-analytics.com
java.net.UnknownHostException: www.google-analytics.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
---->   at com.graphaware.common.ping.GoogleAnalyticsStatsCollector.lambda$post$1(GoogleAnalyticsStatsCollector.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This error repeats **every 5 minutes** (`2017-09-28 08:01:42.295`, `2017-09-28 08:06:42.044`, `2017-09-28 08:11:42.047`, etc.). This makes the log unreadable. This warning should not print a stack trace at all, imo it should be completely silent since the user did not even ask to connect to google-analytics.

**Comment by bachmanm** [comment]
As per docs here, please set https://github.com/graphaware/neo4j-framework

```
com.graphaware.runtime.stats.disabled=true
com.graphaware.server.stats.disabled=true
```

**Comment by davidrapin** [comment]
Thank you, I will add this to the recommended settings!
I think the failure should be silent nonetheless.

**Comment by bachmanm** [comment]
fair enough
