### ISSUE TITLE
Unable to start neo4j server

### ISSUE THREAD

**Issue by shubham-pathak22** [graphaware/neo4j-to-elasticsearch#96]
Hi, I am trying to run neo4j  with graphaware-neo4j-to-elasticsearch plugin. I followed the steps in readme but getting following error

```
2018-01-07 07:39:37.570+0000 INFO  ======== Neo4j 3.3.0 ========
2018-01-07 07:39:37.604+0000 INFO  Starting...
2018-01-07 07:39:38.257+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-01-07 07:39:39.846+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
2018-01-07 07:39:39.865+0000 WARN  Topology change adapter is not available on community edition
2018-01-07 07:39:39.867+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID ES, using com.graphaware.module.es.ElasticSearchModuleBootstrapper
2018-01-07 07:39:39.934+0000 INFO  ElasticSearch index-prefix set to neo4j-index
2018-01-07 07:39:39.934+0000 INFO  ElasticSearch key-property set to uuid
2018-01-07 07:39:39.935+0000 INFO  ElasticSearch force-strings set to false
2018-01-07 07:39:39.936+0000 INFO  ES (re-)initialize until set to NEVER
2018-01-07 07:39:39.936+0000 INFO  Elasticsearch URI set to localhost
2018-01-07 07:39:39.937+0000 INFO  Elasticsearch port set to 9200
2018-01-07 07:39:39.937+0000 INFO  Elasticsearch retry-on-error set to false
2018-01-07 07:39:39.938+0000 INFO  Elasticsearch module queue capacity set to 10000
2018-01-07 07:39:39.938+0000 INFO  Elasticsearch module reindex batch size set to 2000
2018-01-07 07:39:39.939+0000 INFO  Elasticsearch bulk execution set to true
2018-01-07 07:39:39.940+0000 INFO  ElasticSearch index-prefix set to neo4j-index
2018-01-07 07:39:39.940+0000 INFO  ElasticSearch key-property set to uuid
2018-01-07 07:39:39.941+0000 INFO  ElasticSearch force-strings set to false
2018-01-07 07:39:39.941+0000 INFO  Elasticsearch mapping configured with class com.graphaware.module.es.mapping.DefaultMapping
2018-01-07 07:39:39.955+0000 INFO  Registering module ES with GraphAware Runtime.
2018-01-07 07:39:39.956+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
2018-01-07 07:39:40.818+0000 INFO  Shutting down GraphAware Runtime... 
2018-01-07 07:39:40.818+0000 INFO  Shutting down module ES
2018-01-07 07:39:40.818+0000 INFO  Stopping Elasticsearch Writer...
2018-01-07 07:39:40.819+0000 INFO  Shutting down Jest Client...
2018-01-07 07:39:40.819+0000 INFO  Shut down Jest Client.
2018-01-07 07:39:40.819+0000 INFO  Stopped Elasticsearch Writer.
2018-01-07 07:39:40.819+0000 INFO  Terminating task scheduler...
2018-01-07 07:39:40.819+0000 INFO  Task scheduler terminated successfully.
2018-01-07 07:39:40.820+0000 INFO  GraphAware Runtime shut down.
2018-01-07 07:39:40.824+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@83b0d0f' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@83b0d0f' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@83b0d0f' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@83b0d0f' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/shubham/Neo4j/neo4j-community-3.3.0/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@3b96f8b0' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-01-07 07:39:40.824+0000 INFO  Neo4j Server shutdown initiated by request
```
Here is how my directory structure looks like.
```
shubhams-MBP:neo4j-community-3.3.0 shubham$ ls -lh plugins/
total 32424
-rw-r--r--  1 shubham  staff   2.8M  7 Jan 18:31 graphaware-neo4j-to-elasticsearch-3.3.0.51.7.jar
-rw-r--r--@ 1 shubham  staff    13M  7 Jan 18:39 graphaware-server-community-all-3.3.0.51.jar
shubhams-MBP:neo4j-community-3.3.0 shubham$ ./bin/neo4j --version
neo4j 3.3.0
```

Here are changes in conf/neo4j.conf

```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
#ES becomes the module ID:
com.graphaware.module.ES.1=com.graphaware.module.es.ElasticSearchModuleBootstrapper

#URI of Elasticsearch
com.graphaware.module.ES.uri=localhost

#Port of Elasticsearch
com.graphaware.module.ES.port=9200

#optional, Elasticsearch index name, default is neo4j-index
com.graphaware.module.ES.index=neo4j-index

com.graphaware.module.ES.retryOnError=false

#optional, size of the in-memory queue that queues up operations to be synchronised to Elasticsearch, defaults to 10000
com.graphaware.module.ES.queueSize=10000

#optional, size of the batch size to use during re-initialization, defaults to 1000
com.graphaware.module.ES.reindexBatchSize=2000

com.graphaware.module.ES.bulk=true
com.graphaware.module.ES.initializeUntil=0
```

**Comment by ikwattro** [comment]
this is a known issue in 3.3.0, you have to upgrade neo and the plugins to the 3.3.1 version
